version: '3.8'

services:
  fe-java:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:8080
    container_name: fe_java_prod
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:8080
    restart: always
